version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: taskflow-postgres
    restart: always
    environment:
      POSTGRES_DB: taskflow
      POSTGRES_USER: taskflow
      POSTGRES_PASSWORD: taskflow
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: taskflow-rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  task-service:
    build: ./task-service
    container_name: taskflow-task-service
    restart: always
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_NAME: taskflow
      DB_USER: taskflow
      DB_PASSWORD: taskflow
    ports:
      - "8081:8081"

  api-gateway:
    build: ./api-gateway
    container_name: taskflow-api-gateway
    restart: always
    depends_on:
      - task-service
      - rabbitmq
    environment:
      TASK_SERVICE_URL: http://task-service:8081
      RABBITMQ_HOST: rabbitmq
    ports:
      - "8080:8080"

  notification-worker:
    build: ./notification-worker
    container_name: taskflow-notification-worker
    restart: always
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST: rabbitmq
